### PR TITLE
Make Context and Camera : Sync

### LINKED ISSUE #55: Task future is not multithreading-friendly
Looks like right now `Context`, `Camera` and `Task` is `Send` but not `Sync`, which makes it hard to use in many APIs that expect being able to check the future status from an arbitrary thread.

For example, trying to use such future inside a `tokio::spawn` API:

```rust
  tokio::task::spawn(async move {
    let camera = Context::new()?.autodetect_camera().await?;
    // TODO
    Ok(())
  });
```

 will fail with something like:

```
error: future cannot be sent between threads safely
   --> examples/drop_camera.rs:8:22
    |
8   |     tokio::task::spawn(async move {
    |  ______________________^
9   | |     let camera = Context::new()?.autodetect_camera().await?;
10  | |     // TODO
11  | |     Ok(())
12  | |   });
    | |___^ future created by async block is not `Send`
    |
    = help: the trait `std::marker::Sync` is not implemented for `(dyn gphoto2::context::ProgressHandler + std::marker::Send + 'static)`
note: future is not `Send` as this value is used across an await
   --> examples/drop_camera.rs:9:53
    |
9   |     let camera = Context::new()?.autodetect_camera().await?;
    |                  ---------------                    ^^^^^^ await occurs here, with `Context::new()?` maybe used later
    |                  |
    |                  has type `&gphoto2::Context` which is not `Send`
note: `Context::new()?` is later dropped here
   --> examples/drop_camera.rs:9:60
    |
9   |     let camera = Context::new()?.autodetect_camera().await?;
    |                                                            ^
help: consider moving this into a `let` binding to create a shorter lived borrow
   --> examples/drop_camera.rs:9:18
    |
9   |     let camera = Context::new()?.autodetect_camera().await?;
    |                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
note: required by a bound in `tokio::spawn`
   --> /home/rreverser/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/task/spawn.rs:163:21
    |
163 |         T: Future + Send + 'static,
    |                     ^^^^ required by this bound in `tokio::spawn`
```

Seems the only reason those APIs are not `Sync` is because of progress handlers, which are only constrained by `Send`. It makes sense, since progress handlers are usually mutating the environment, but I wonder if it would make sense to turn them into channels similarly to `waker` field and other operations, so that background gphoto2 thread sends progress updates via `Sender`, and receivers on any thread handle them.

### PR DESCRIPTION
**Pull request by RReverser**
Fixes #55 by wrapping the handlers into a Mutex. This makes Context and Camera safe to access from arbitrary threads for read-only access.

### CODE REVIEW

**Review by maxicarlos08 — APPROVED** [review]
lgtm!

File: src/camera.rs [hunk 1]
```diff
@@ -378,6 +378,12 @@ impl Camera {
 
 #[cfg(all(test, feature = "test"))]
 mod tests {
+  // Compile-only test to ensure that Camera is Send + Sync.
+  const _: () = {
+    const fn assert_send_sync<T: Send + Sync>() {}
```
Comment (maxicarlos08) [inline src/camera.rs:383]: This is nice, didn't know it was a thing before :)

**Comment by RReverser** [comment]
Can you publish an update to crates.io please?

**Comment by maxicarlos08** [comment]
Yes, working on it

**Comment by RReverser** [comment]
Eh, this is a non-breaking bugfix, 3.1.1 would've been fine :) But thanks anyway.
